[package]
name = "login-client"
version = "0.1.0"
authors = ["wagnrd"]
edition = "2021"

[dependencies]
relm4 = { version = "0.6.0-beta.1", features = ["libadwaita", "gnome_44"] }
relm4-components = "0.6.0-beta.1"