on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Build and release
jobs:
  build-linux:
    if: false
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
      - name: Install dependencies
        run: sudo apt install libgtk-4-dev build-essential libadwaita-1-dev
      - name: Build
        run: |
          cargo build -r
          mv ./target/release/work-tracker ./target/release/work-tracker-linux
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/work-tracker-linux

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
      - name: Install dependencies
        run: brew install gtk4 libadwaita
      - name: Build
        run: |
          cargo build -r
          mv ./target/release/work-tracker ./target/release/work-tracker-macos
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/work-tracker-macos
