on:
  push:
    branches:
      - main

name: Build and release
jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
      - name: Install dependencies
        run: sudo apt install libgtk-4-dev build-essential libadwaita-1-dev
      - name: Build
        run: cargo build -r
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: v0.1
          files: ./target/release/work-tracker

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          components: rustc, rust-std
      - name: Install dependencies
        run: brew install gtk4 libadwaita
      - name: Build
        run: cargo build -r
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: v0.1
          files: ./target/release/work-tracker
